LATEST_CFG_URL: str
LOCAL_CFG_PATH: str
REPO_URL: str

def _get_version_from_cfg(content: str) -> str | None: ...
def _get_latest_version() -> str | None: ...
def _get_local_version() -> str | None: ...
def _check_mod_version() -> None: ...