from abc import ABCMeta
from enum import Enum, EnumMeta, IntEnum, Flag, IntFlag

__all__ = ["ABCEnumMeta", "ABCEnum", "ABCIntEnum", "ABCFlag", "ABCIntFlag"]

class ABCEnumMeta(ABCMeta, EnumMeta): ...

class ABCEnum(Enum, metaclass=ABCEnumMeta): ...

class ABCIntEnum(IntEnum, metaclass=ABCEnumMeta): ...

class ABCFlag(Flag, metaclass=ABCEnumMeta): ...

class ABCIntFlag(IntFlag, metaclass=ABCEnumMeta): ...
